export const FETCH_TODOS_START = 'FETCH_TODOS_START'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_ERROR = 'FETCH_TODOS_ERROR'

export const CREATE_TODO_TASK = 'CREATE_TODO_TASK'
export const CREATE_TODO_ERROR = 'CREATE_TODO_ERROR'

export const COMPLETED_TODO_SUCCESS = 'COMPLETED_TODO_SUCCESS'
export const COMPLETED_TODO_ERROR = 'COMPLETED_TODO_ERROR'

export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS'
export const REMOVE_TODO_ERROR = 'REMOVE_TODO_ERROR'
